modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.github.com/antonhibl/astrochem-forge/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.github.com/antonhibl/astrochem-forge"
logoFile="icon.png"
authors="${mod_authors}"
description='''Add-on for Ad Astra, Alchemistry and ChemLib for Forge 1.19.2!'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="alchemistry"
mandatory=true
versionRange="[1.19.2-2.0.8,1.19.2-2.3.2]"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="chemlib"
mandatory=true
versionRange="[1.19.2-2.0.8,1.19.2-2.0.19]"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ad_astra"
mandatory=true
versionRange="[1.12.6,1.12.7]"
ordering="AFTER"
side="BOTH"